# tasks file for apt-file
---
- name: install
  apt:
    name: apt-file
    state: latest
    update_cache: true
    cache_valid_time: "{{ apt_update_cache_valid_time | default(3600) }}"
  register: result
  tags:
    - configuration
    - apt-file
    - apt-file-install

- name: run apt-file update (once)
  shell: test -x /usr/bin/apt-file && /usr/bin/apt-file update
  when: result | changed
  tags:
    - configuration
    - apt-file
    - apt-file-update

- name: add (daily) cron task
  cron:
    name: "apt-file update"
    job: "test -x /usr/bin/apt-file && /usr/bin/apt-file update"
    special_time: daily
    cron_file: apt-file
    user: root
  when: apt_file_update_daily
  tags:
    - configuration
    - apt-file
    - apt-file-cron-d
