# tasks file for apt-file
---
- name: install
  apt:
    name: "{{ apt_file_dependencies }}"
    state: "{{ apt_install_state | default('latest') }}"
    update_cache: true
    cache_valid_time: "{{ apt_update_cache_valid_time | default(3600) }}"
  register: _result
  tags:
    - configuration
    - apt-file
    - apt-file-install

- name: run apt-file update (once)
  shell: "{{ apt_file_update_job }}"
  when: _result is changed
  tags:
    - configuration
    - apt-file
    - apt-file-update

- name: add (daily) cron task
  cron:
    name: "apt-file update"
    job: "{{ apt_file_update_job }}"
    special_time: daily
    cron_file: apt-file
    user: root
  when: apt_file_update_daily
  tags:
    - configuration
    - apt-file
    - apt-file-cron-d
