# tasks file
---
- name: install
  ansible.builtin.apt:
    name: "{{ apt_file_dependencies }}"
    state: "{{ apt_install_state | default('latest') }}"
    update_cache: true
    cache_valid_time: "{{ apt_update_cache_valid_time | default(3600) }}"
  register: _result
  tags:
    - configuration
    - apt-file
    - apt-file-install

- name: run apt-file update (once)
  ansible.builtin.shell: >
    {{ apt_file_update_job }}
  when: _result is changed
  tags:
    - configuration
    - apt-file
    - apt-file-update

- name: add (daily) cron task
  ansible.builtin.cron:
    name: "apt-file update"
    job: "{{ apt_file_update_job }}{{ apt_file_quiet | ternary(' ' + apt_file_quietness + ' /dev/null', '') }}"
    special_time: daily
    cron_file: apt-file
    user: root
  when: apt_file_update_daily
  tags:
    - configuration
    - apt-file
    - apt-file-cron-d
